#!/bin/bash

adduser postgres
yum -y install postgresql-libs postgresql postgresql-server postgresql-devel
chown postgres /var/lib/pgsql9/
su - postgres -c "curl https://raw.github.com/MattParker89/PostgresInstall/master/postgres_script | bash"
service postgresql start
service postgresql status
sudo chkconfig postgresql on
exit

